### ISSUE TITLE
Item wont build on windows with rm -rf NPM script. 

### ISSUE THREAD

**Issue by gljohn** [qontu/component-store#1]
Cannot build on windows, rm -rf not a valid command in power shell or command prompt. Could you use [rimraf](https://www.npmjs.com/package/rimraf)?

Error output:
`'rm' is not recognized as an internal or external command, operable program or batch file.`

**Comment by tonivj5** [comment]
Hey, I'm surprised that you're using this module if it hasn't documentation nor README 😆 It is solved by https://github.com/qontu/component-store/pull/2
