### ISSUE TITLE
IE Error Expected Identifier

### ISSUE THREAD

**Issue by MThomas564** [qontu/component-store#3]
Error when using as a dependency of ngx-inline-editor in IE. 

Error:
`Expected identifier`
`File: vendor.2885b84628082281cb07.js, Line: 42778, Column: 17`

Line refers to:
`function Action(...actionsClasses) {`
Which is from src/decorators/action.ts

The spread operator requires a further polyfil, can be seen in this [issue](https://github.com/jayphelps/core-decorators/issues/81) or to be changed to be functional in TypeScript

**Comment by tonivj5** [comment]
I think if we changing the target property from es6 to es5 in [tsconfig.json](https://github.com/qontu/component-store/blob/master/tsconfig.json#L11), it's enough to fix this issue

**Comment by tonivj5** [comment]
Anddd... 😋

> Hey, I'm surprised that you're using this module if it hasn't documentation nor README 😆
